<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <Description>Used to test library implementations</Description>
        <Authors>DexrnZacAttack</Authors>
        <Copyright>DexrnZacAttack</Copyright>
        <PackageProjectUrl>https://git.dexrn.me/Dexrn/Shiki/</PackageProjectUrl>
        <PackageLicenseUrl>https://git.dexrn.me/Dexrn/Shiki/src/branch/main/LICENSE</PackageLicenseUrl>
        <RepositoryUrl>https://git.dexrn.me/Dexrn/Shiki/</RepositoryUrl>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
        <Version>1.0.0</Version>
        <PackageReleaseNotes>- Initial Creation
            - Used to test library implementations
        </PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
        <PackageReference Include="NUnit" Version="4.6.1" />
        <PackageReference Include="NUnit.Analyzers" Version="4.14.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shiki.Common\Shiki.Common.csproj" />
    </ItemGroup>

</Project>
