#nullable enable

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Shiki.CodeGenerator.Generator.Event.Observe;

[Generator]
public class PubliclyImmutableObservableGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
                              .ForAttributeWithMetadataName("Shiki.Common.Event.Observe.PubliclyImmutableObservableAttribute",
                                                            (node, _) =>
                                                                node is VariableDeclaratorSyntax
                                                                     or PropertyDeclarationSyntax,
                                                            (ctx, _) => ctx.TargetSymbol
                                                           );

        context.RegisterSourceOutput(provider, Generate);
    }

    private void Generate(SourceProductionContext context, ISymbol symbol)
    {
        INamedTypeSymbol? parentObject = symbol.ContainingType;
        if (parentObject == null)
        {
            throw new Exception("No parent class/object is associated with this field/property");
        }

        ITypeSymbol? type = symbol switch
        {
            IFieldSymbol field       => field.Type,
            IPropertySymbol property => property.Type,
            _                        => null
        };

        ITypeSymbol? genericType = (type as INamedTypeSymbol)?.TypeArguments.FirstOrDefault();
        if (genericType == null)
        {
            throw new ArgumentException("Generic type is null", nameof(genericType));
        }

        string genericTypeName = genericType.ToDisplayString();
        string fieldName = symbol.Name;

        //is there not nicer way to do this
        //I wanted tree-like generation where I can define file with namespaces and usings and then class with fields and properties
        //and then turn it into file
        string source = $$"""
                          using Shiki.Common.Event.Observe;
                          using {{genericType?.ContainingNamespace.ToDisplayString()}};

                          namespace {{parentObject.ContainingNamespace.ToDisplayString()}};

                          /* AUTOGENERATED, DO NOT MODIFY, OTHERWISE YOUR CHANGES WILL GO INTO GARBAGE AS SOON AS PROJECT IS REBUILT */
                          public partial class {{parentObject.Name}}
                          {
                              public Observable<{{genericTypeName}}> {{GetPublicName(fieldName)}} => {{fieldName}}; 
                          }

                          """;

        context.AddSource($"{parentObject.Name}.{fieldName}.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private string GetPublicName(string name)
    {
        string noPrefix = name switch
        {
            not null when name.StartsWith("m_") => name.Substring(2), //do people still use this
            not null when name.StartsWith("_")  => name.Substring(1),
            _                                   => name!
        };

        string publicName = char.ToUpper(noPrefix[0]) + noPrefix.Substring(1);

        if (publicName == name)
        {
            publicName = "Observable" + name;
        }

        return publicName;
    }
}