<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Description>C# commons lib for stuff I copy around or overengineer</Description>
        <Copyright>DexrnZacAttack</Copyright>
        <Company>DexrnZacAttack</Company>
        <Authors>DexrnZacAttack</Authors>
        <PackageProjectUrl>https://git.dexrn.me/Dexrn/Shiki/</PackageProjectUrl>
        <PackageLicenseUrl>https://git.dexrn.me/Dexrn/Shiki/src/branch/main/LICENSE</PackageLicenseUrl>
        <RepositoryUrl>https://git.dexrn.me/Dexrn/Shiki/</RepositoryUrl>
        <AssemblyVersion>2.1.0</AssemblyVersion>
        <FileVersion>2.1.0</FileVersion>
        <Version>2.1.0</Version>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <LangVersion>14</LangVersion>

        <PackageReleaseNotes>### `Identifier`
- Removed accidental leftover debug line in the constructor
- Created `Identifier(string, ImmutableArray&lt;string&gt;)` constructor
   - Other constructors now call to this one, in addition to reusing `ImmutableArray&lt;string&gt;.Empty` if an empty path is passed.

### RangeObservableCollection
- Now calls OnCollectionChanged with `NotifyCollectionChangedAction.Add` w/ new items, instead of `NotifyCollectionChangedAction.Reset`.

            ## Breaking Changes
### IdentifierNamespace
- `operator string` is now `explicit`</PackageReleaseNotes>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Shiki.CodeGenerator\Shiki.CodeGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.9" />
      <PackageReference Include="Unidecode.NET" Version="2.2.1" />
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="Util\Serialization\" />
    </ItemGroup>
    
    <ItemGroup>
      <Compile Remove="Result\.ErrorCodeResult_NEW.cs" />
      <None Include="Result\.ErrorCodeResult_NEW.cs" />
    </ItemGroup>
    
</Project>
