using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Shiki.CodeGenerator.Core;

#nullable enable

namespace Shiki.CodeGenerator.Generator.Factory;

[Generator]
public class FactoryConstructableAttributeImplGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
                              .CreateSyntaxProvider(
                                                    (node, _) =>
                                                        node is ClassDeclarationSyntax or RecordDeclarationSyntax
                                                         or StructDeclarationSyntax,
                                                    (ctx, _) =>
                                                    {
                                                        if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not
                                                            INamedTypeSymbol c) return null;

                                                        List<Symbol> ctors =
                                                        [
                                                            .. from ctor in c.Constructors
                                                               let isFactoryConstructable = HasAttribute(ctor)
                                                               where isFactoryConstructable
                                                               select Symbol.FromMethodSymbol(ctor)
                                                        ];

                                                        return ctors;
                                                    }
                                                   );
        
        context.RegisterSourceOutput(provider, GenerateAll);
    }

    private bool HasAttribute(ISymbol symbol) => symbol.GetAttributes()
                                                       .Any(a =>
                                                                a.AttributeClass
                                                                ?.ToDisplayString() ==
                                                                "Shiki.Common.Factory.FactoryConstructableAttribute");

    private void GenerateAll(SourceProductionContext context, IEnumerable<Symbol>? symbols)
    {
        if (symbols == null)
            return;
        
        foreach (Symbol symbol in symbols)
        {
            Generate(context, symbol);
        }
    }

    private void Generate(SourceProductionContext context, Symbol symbol)
    {
        // while (!Debugger.IsAttached){}

        string usings = !symbol.Imports.IsEmpty ? "\n" : "";
        usings += string.Join("\n", symbol.Imports.Select(i => $"using {i};"));
        
        string tp = string.Join(", ", symbol.Params.Select(p => p.TypeName).Prepend(symbol.FullClassName));

        string docs = "/// <inheritdoc/>";
        if (symbol.Documentation != null)
        {
            XElement member = XElement.Parse(symbol.Documentation);
            docs = "///" + string.Join("\n    ///", member.Nodes().SelectMany(n => n.ToString().Split([
                "\r\n", "\r", "\n"
            ], StringSplitOptions.None).Select(l => l.Trim())));
        }

        string p = string.Join(", ", symbol.Params.Select(p => p.Name));
        
        StringBuilder sb = new StringBuilder();
        sb.AppendLine($"#nullable enable")
          .AppendLine()
          .AppendLine($"using Shiki.Common.Factory;{usings}")
          .AppendLine()
          .AppendLine($"namespace {symbol.Namespace};")
          .AppendLine()
          .AppendLine("/* <auto-generated /> */");
        
        foreach (Symbol sym in symbol.ContainingClassTypes.Reverse())
        {
            sb
               .AppendLine($"{sym.Accessibility} {sym.ClassKind} {sym.FullClassName} {(symbol.TemplateParams.Any(t => t.Constraint != null) ? "\n" + string.Join("\n", symbol.TemplateParams.Where(t => t.Constraint != null).Select(t => t.Constraint)) : "")}\n")
               .AppendLine("{");
        }

        
        sb
           .AppendLine($"{symbol.Accessibility} {symbol.ClassKind} {symbol.FullClassName} : IFactoryConstructable<{tp}> {(symbol.TemplateParams.Any(t => t.Constraint != null) ? "\n" + string.Join("\n", symbol.TemplateParams.Where(t => t.Constraint != null).Select(t => t.Constraint)) : "")}")
           .AppendLine("{")
           .AppendLine($"{docs}")
           .AppendLine($"public static {symbol.FullClassName} CreateInstance({string.Join(", ", symbol.Params.Select(p => $"{p.TypeName} {p.Name}"))}) => new {symbol.FullClassName}({p}); ")
           .AppendLine("}");
        
        foreach (Symbol unused in symbol.ContainingClassTypes)
        {
            sb.AppendLine("}");
        }
        
        //is there not nicer way to do this
        //I wanted tree-like generation where I can define file with namespaces and usings and then class with fields and properties
        //and then turn it into file
        string source = sb.ToString();
        
        context.AddSource($"FactoryConstructable.{symbol.Namespace}.{ToFriendlyFilename(symbol.FullClassName)}.{ToFriendlyFilename(string.Join(".", symbol.Params.Select(p => p.TypeName)))}.g.cs",
                          SourceText.From(source, Encoding.UTF8));
    }

    private static string ToFriendlyFilename(string str) => Uri
                                                           .EscapeDataString(str
                                                                            .Replace("?", "_nullable")
                                                                            .Replace("<", "_tr_")
                                                                            .Replace(">", "_tl")
                                                                            .Replace(",", "_cm_")
                                                                            .Replace(" ", "")).Replace("%", "_");
}